### PR TITLE
resolves #23 add option to export to image

### LINKED ISSUE #23: Add option to export slide images to disk
Add an option that exports each slide as an image as it is creating the PDF.

The benefit of exporting each slide to an image is that those images can then be used independently to create other documents, such as a handout that includes slide notes under each slide image.

### PR DESCRIPTION
**Pull request by mojavelinux**
- export slides as images if format argument or output file extension is png or jpg

### CODE REVIEW

**Comment by mojavelinux** [comment]
Here's a rough prototype of this idea.This is just rough sketch to feel out what requirements we'll need. It prompts me to think about how exactly we want to accept this information from the user. In this prototype, I decided to make the output format mutually exclusive (pdf or image) and use the output file name as the base of the image file names.

**Comment by mojavelinux** [comment]
It might be better to pass the format to the Browser class instead of deriving it in the constructor. wdyt?

**Comment by mojavelinux** [comment]
I think we should move the write logic to a Writer class for each format to decouple the writing of the output from the Browser.

**Comment by mojavelinux** [comment]
Stay tuned, I've got some updates that makes this cleared and gets jpg export working. I haven't done the refactoring to extract a SlideWriter yet, but with my local changes I'm happy with the fact that the export makes the right thing. Will push soon.

**Comment by mojavelinux** [comment]
I managed to get a 400+ slide deck (don't ask) exported in under 5 minutes, which is pretty amazing if you think about the fact that it's like a week of training :)

**Comment by melix** [comment]
Cool! The good old `AtomicInteger` trick :)

Do you think your PR is good to go now?

**Comment by mojavelinux** [comment]
Not yet, I haven't pushed my latest changes. That's first on my hacking list today. I'll post once I've pushed the update.

**Comment by mojavelinux** [comment]
The pull request is now updated. The only thing that hasn't yet been done is to refactor the slide write logic into a separate object. It's pretty clear we need that for how many conditional statements and variables we have in the Browser class :) However, it's reasonable to do that as a follow-up step.

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
